# $FreeBSD: releng/12.1/lib/csu/tests/Makefile 352394 2019-09-16 13:41:24Z andrew $

SUBDIR=		dso
TESTS_SUBDIRS=	dynamic
TESTS_SUBDIRS+=	dynamiclib
TESTS_SUBDIRS+=	static

SUBDIR_DEPEND_dynamiclib=dso

.include <bsd.test.mk>
