# $FreeBSD: releng/12.1/lib/csu/tests/Makefile.tests 352394 2019-09-16 13:41:24Z andrew $

ATF_TESTS_C+=	init_test
ATF_TESTS_C+=	fini_test
ATF_TESTS_CXX+=	cxx_constructors

WARNS?=		3

.if exists(${.CURDIR:H:H}/${MACHINE_ARCH})
CFLAGS+= -I${.CURDIR:H:H}/${MACHINE_ARCH}
.else
CFLAGS+= -I${.CURDIR:H:H}/${MACHINE_CPUARCH}
.endif
