#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: releng/12.1/usr.sbin/pmcstudy/Makefile 352094 2019-09-09 18:27:52Z imp $

PROG=	pmcstudy
MAN=	pmcstudy.8
SRCS= pmcstudy.c eval_expr.c
CFLAGS+= -Wall ${WERROR}

BINDIR= /usr/bin

.include <bsd.prog.mk>

