# $FreeBSD: releng/12.1/sys/modules/mac_partition/Makefile 314651 2017-03-04 10:10:17Z ngie $

.PATH: ${SRCTOP}/sys/security/mac_partition

KMOD=	mac_partition
SRCS=	vnode_if.h \
	mac_partition.c

.include <bsd.kmod.mk>
