# $FreeBSD: releng/12.1/cddl/usr.sbin/dtrace/tests/i386/Makefile 348081 2019-05-22 03:42:03Z markj $

TESTSDIR=	${TESTSBASE}/cddl/usr.sbin/dtrace/i386
TESTS_SUBDIRS+= arrays \
		funcs \
		pid \
		ustack

.PATH:		${.CURDIR:H:H:H:H:H}/tests
KYUAFILE=	YES

.include <bsd.test.mk>
