# $FreeBSD: releng/12.1/usr.bin/bzip2recover/Makefile 351666 2019-09-01 16:57:19Z markj $

BZ2DIR=	${SRCTOP}/contrib/bzip2
.PATH: ${BZ2DIR}

PROG=	bzip2recover
MAN=

NO_WMISSING_VARIABLE_DECLARATIONS=

.include <bsd.prog.mk>
