# $FreeBSD: releng/12.1/cddl/usr.sbin/zfsd/Makefile 348138 2019-05-23 01:09:10Z ngie $

.include <src.opts.mk>

.include "Makefile.common"

PROG_CXX=	zfsd
MAN=		zfsd.8

HAS_TESTS=
SUBDIR.${MK_GOOGLETEST}+= tests

.include <bsd.prog.mk>
