# $FreeBSD: releng/12.1/stand/sparc64/Makefile 345327 2019-03-20 15:34:40Z mmacy $

NO_OBJ=t

.include <bsd.init.mk>

SUBDIR.yes=	boot1 loader
SUBDIR.${MK_LOADER_ZFS}+=zfsboot

.include <bsd.subdir.mk>
