# $FreeBSD: releng/12.1/usr.sbin/bluetooth/iwmbtfw/Makefile 352102 2019-09-09 18:57:17Z wulf $

CONFS=		iwmbtfw.conf
CONFSDIR=       /etc/devd
PROG=		iwmbtfw
MAN=		iwmbtfw.8
LIBADD+=	usb
SRCS=		main.c iwmbt_fw.c iwmbt_hw.c

.include <bsd.prog.mk>
