# $FreeBSD: releng/12.1/sys/modules/arm_ti/Makefile 349096 2019-06-16 01:22:44Z ian $
# Build modules specific to Texas Instruments ARM SoCs.

SUBDIR = \
	../am335x_dmtpps \
	am335x_ehrpwm \
	ti_i2c \
	
.include <bsd.subdir.mk>
