# $FreeBSD: releng/12.1/usr.bin/locale/tests/Makefile 352416 2019-09-16 16:17:29Z yuripv $

PACKAGE=	tests

ATF_TESTS_SH=	locale_test

${PACKAGE}FILES+=	k_flag_posix_monetary.out
${PACKAGE}FILES+=	k_flag_posix_numeric.out
${PACKAGE}FILES+=	k_flag_posix_time.out
${PACKAGE}FILES+=	k_flag_posix_messages.out
${PACKAGE}FILES+=	no_flags_posix_monetary.out
${PACKAGE}FILES+=	no_flags_posix_numeric.out
${PACKAGE}FILES+=	no_flags_posix_time.out
${PACKAGE}FILES+=	no_flags_posix_messages.out

.include <bsd.test.mk>
