# $FreeBSD: releng/12.1/lib/libc/tests/stdlib/dynthr_mod/Makefile 343599 2019-01-31 02:49:24Z kevans $

SHLIB_NAME=	dynthr_mod.so
SHLIBDIR=	${TESTSDIR}
SRCS=		dynthr_mod.c
LIBADD=		pthread

TESTSDIR:=	${TESTSBASE}/${RELDIR:C/libc\/tests/libc/:H}


.include <bsd.lib.mk>
