# $FreeBSD: releng/12.1/sys/modules/i2c/Makefile 351869 2019-09-05 16:37:10Z ian $

SUBDIR = \
	ads111x \
	controllers \
	cyapa \
	ds1307 \
	ds13rtc \
	ds1672 \
	ds3231 \
	icee \
	if_ic \
	iic \
	iicbb \
	iicbus \
	iicsmb \
	isl \
	isl12xx \
	jedec_dimm \
	nxprtc \
	rtc8583 \
	s35390a \
	smb \
	smbus \

.include <bsd.subdir.mk>
