# $FreeBSD: releng/12.1/lib/libc/tests/regex/Makefile 341745 2018-12-08 19:45:05Z yuripv $

PACKAGE=	tests

# local test cases
ATF_TESTS_SH+=	multibyte

.include "Makefile.inc"
.include "${.CURDIR:H}/Makefile.netbsd-tests"
.include <bsd.test.mk>
