# $FreeBSD: releng/12.1/lib/googletest/Makefile 344336 2019-02-20 03:07:11Z ngie $

.include <src.opts.mk>

SUBDIR+=		gtest
SUBDIR+=		.WAIT
SUBDIR+=		gmock
SUBDIR+=		.WAIT
SUBDIR+=		gmock_main
SUBDIR+=		gtest_main

SUBDIR.${MK_TESTS}+=	tests

.include <bsd.subdir.mk>
