# $FreeBSD: releng/12.1/sys/modules/ntb/ntb_hw_amd/Makefile 349594 2019-07-02 05:25:18Z mav $

.PATH:  ${SRCTOP}/sys/dev/ntb/ntb_hw

KMOD    = ntb_hw_amd
SRCS    = ntb_hw_amd.c
SRCS += device_if.h bus_if.h pci_if.h ntb_if.h

.include <bsd.kmod.mk>
