# $FreeBSD: releng/12.1/sys/modules/allwinner/Makefile 350602 2019-08-05 18:05:22Z manu $
# Build modules specific to Allwinner.

SUBDIR = \
	aw_pwm \
	aw_rtc \
	aw_rsb \
	aw_sid \
	aw_spi \
	aw_thermal \
	axp81x \
	if_awg

.include <bsd.subdir.mk>
